{
    'name': 'Car Rental',
    'version': '1.0',
    'category': 'Services',
    'summary': 'Car Rental Management System',
    'description': """Car Rental Management System""",
    'author': 'Tersom',
    'depends': ['base','mail'],
    'data': [
        'security/car_rental_security.xml',
        'security/ir.model.access.csv',
        'views/car_rental_category_views.xml',
        'views/car_rental_feature_views.xml',
        'views/car_rental_vehicle_views.xml',
        'views/car_rental_order_views.xml',
        'views/res_partner_views.xml',
        'wizard/car_rental_return_wizard.xml',
        'report/report_paperformat.xml',
        'report/car_rental_report_templates.xml',
        'report/car_rental_report.xml',
        'report/car_rental_report_terms.xml',
        'data/car_rental_sequence.xml',
        'data/car_rental_cron.xml',
        'wizard/car_rental_export_wizard.xml',
        'views/car_rental_menus.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'assets': {
    'web.assets_backend': [
        'car_rental/static/src/js/vehicle_status_badge.js',
        'car_rental/static/src/xml/vehicle_status_badge.xml',
        'car_rental/static/src/scss/vehicle_status_badge.scss',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
